# Generated by Django 5.2 on 2025-04-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resturant_causine_rating_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='announced',
            new_name='saled_at',
        ),
    ]
