# Generated by Django 5.2 on 2025-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rating_stars_alter_resturant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='causine',
            field=models.CharField(choices=[('IN', 'Indian'), ('IT', 'Italian'), ('CH', 'Chinese'), ('MX', 'Mexican'), ('AM', 'American'), ('EG', 'Egyption')], default='AM', max_length=2),
        ),
    ]
